name = "rgat_nature_paper"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["RgatNaturePaper"]

[leanOptions]
pp.unicode.fun = true                  # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = false
maxSynthPendingDepth = 3
linter.unusedSimpArgs = false
linter.unnecessarySimpa = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.24.0"

[[lean_lib]]
name = "RgatNaturePaper"
